### ISSUE TITLE
vagrant provision fails on po box

### ISSUE THREAD

**Issue by mhidas** [aodn/chef#289]
Unable to provision the project officers vagrant box using the latest chef code. Seems to be caused by #284 

```
$ vagrant provision po

...

==> po: ================================================================================
==> po: Recipe Compile Error in /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/imos_postfix/recipes/default.rb
==> po: ================================================================================
==> po: 
==> po: Chef::Exceptions::ValidationFailed
==> po: ----------------------------------
==> po: Data Bag Items must contain a Hash or Mash!
==> po: 
==> po: Cookbook Trace:
==> po: ---------------
==> po:   /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/imos_postfix/recipes/default.rb:18:in `from_file'
==> po: 
==> po: Relevant File Content:
==> po: ----------------------
==> po: /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/imos_postfix/recipes/default.rb:
==> po: 
==> po:  11:  
==> po:  12:  node.override['postfix']['smtp_sasl_auth_enable']= 'yes'
==> po:  13:  node.override['postfix']['smtp_sasl_security_options']= 'noanonymous'
==> po:  14:  node.override['postfix']['smtp_sasl_password_maps']= 'hash:/etc/postfix/sasl_passwd'
==> po:  15:  node.override['postfix']['smtp_tls_cafile']= "/opt/chef/embedded/ssl/certs/cacert.pem"
==> po:  16:  node.override['postfix']['smtp_tls_security_level']= 'encrypt'
==> po:  17:  
==> po:  18>> sendgrid_vars = Chef::DataBagItem.load('passwords','sendgrid')
==> po:  19:  node.override['postfix']['relayhost']= "[" + sendgrid_vars['host'] + "]:" + sendgrid_vars['port'].to_s
==> po:  20:  node.override['postfix']['smtp_sasl_passwd']= sendgrid_vars['password']
==> po:  21:  node.override['postfix']['smtp_sasl_user_name']= sendgrid_vars['username']
==> po:  22:  
```

**Comment by lbesnard** [comment]
@mhidas  see https://github.com/aodn/backlog/issues/321

**Comment by mhidas** [comment]
Failing again... (on current master).

```
==> po:     ================================================================================
==> po:     Error executing action `deploy` on resource 'imos_artifacts_deploy[aatams_sattag_dm-aatams_sattag_dm]'
==> po:     
==> po: ================================================================================
==> po:     
==> po: 
==> po:     TypeError
==> po:     ---------
==> po:     no implicit conversion of nil into String
==> po:     
==> po: 
==> po:     
==> po: Cookbook Trace:
==> po:     ---------------
==> po: 
==> po:     
==> po: /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/imos_artifacts/libraries/fetcher_jenkins.rb:86:in `+'
==> po:     
==> po: /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/imos_artifacts/libraries/fetcher_jenkins.rb:86:in `cache'
==> po:     /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/imos_artifacts/libraries/fetcher.rb:28:in `fetch_jenkins_artifact'
==> po:     /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/imos_artifacts/libraries/fetcher.rb:21:in `fetch_artifact'
==> po:     
==> po: /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/imos_artifacts/providers/deploy.rb:18:in `block in class_from_file'
==> po:     
==> po: 
==> po:     
==> po: Resource Declaration:
==> po:     
==> po: ---------------------
==> po:     # In /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/talend/providers/job.rb
==> po:     
==> po:     
==> po: 110:   imos_artifacts_deploy job_name do
==> po:     111:     install_dir                job_java_dir
==> po: 
==> po:     112:     artifact_id                new_resource.artifact_id
==> po:     113:     artifact_manifest          new_resource.artifact_manifest
==> po:     
==> po: 114:     file_destination           ::File.join(job_dir, "#{new_resource.common_name}.zip")
==> po:     
==> po: 115:     # Remove redundant directory structure
==> po:     116:     remove_top_level_directory true
==> po:     
==> po: 117:     owner                      'root'
==> po:     
==> po: 118:     group                      'root'
==> po:     
==> po: 119:   end
==> po:     120: end
==> po:     
==> po: 
==> po:     
==> po: Compiled Resource:
==> po:     
==> po: ------------------
==> po:     
==> po: # Declared in /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/talend/providers/job.rb:110:in `block in class_from_file'
==> po:     
==> po:     imos_artifacts_deploy("aatams_sattag_dm-aatams_sattag_dm") do
==> po:     
==> po:   action :deploy
==> po:       retries 0
==> po:       retry_delay 2
==> po: 
==> po:       default_guard_interpreter :default
==> po: 
==> po:       declared_type :imos_artifacts_deploy
==> po:       cookbook_name :talend
==> po:       install_dir "/usr/local/talend/jobs/aatams_sattag_dm-aatams_sattag_dm/java"
==> po: 
==> po:       file_destination "/usr/local/talend/jobs/aatams_sattag_dm-aatams_sattag_dm/aatams_sattag_dm.zip"
==> po:     
==> po:   artifact_manifest {"id"=>"talend_build/aatams_sattag_dm_harvester_Latest.zip", "job"=>"talend_build", "filename"=>"aatams_sattag_dm_harvester_Latest.zip"}
==> po:     
==> po:   owner "root"
==> po:       group "root"
==> po:     
==> po:   artifact_id "aatams_sattag_dm-aatams_sattag_dm"
==> po:       remove_top_level_directory true
==> po:     
==> po: end
```

I have tried removing "aatams_sattag_dm" from nodes/po.json but I still get the same error.

**Comment by pmbohm** [comment]
@mhidas @lbesnard I had the PO box running from scratch. `vagrant up po`  **Not a provision**. I cant be expected to fix an individual running PO box, but you should be able to get a fresh one going.

Loz told me about the jenkins job to test run the PO box. It has a fatal error running right at the start which I think is unrelated. 

I note that the jenkins job uses `bin/po-box.sh` which i'm running now to see if it gets to the end, so far so good........   **nope Fatal error at aatams_sattag_dm-aatams_sattag_dm**

**Comment by pmbohm** [comment]
After removing `aatams_sattag_dm` the same error occurs on the next harvester alphabetically `aatams_sattag_nrt` so ther is a bigger issue here now.

**Comment by lwgordonimos** [comment]
I believe there are two issues with this:

1) missing artifacts from the talend_build job in Jenkins - this should now be fixed, as the artifacts were rebuilt with a "rebuild all" in talend_build on Friday

2) the build previously took place as a remote build on 6-its-hob.emii.org.au which no longer exists - can anyone think of an existing non-production box which would be suitable to be a secondary Jenkins build node for this (possible other things)? The primary Jenkins server is stressed enough without trying to run Vagrant on it as well, so I believe a second node is still required, unless we bumped the resources substantially on 15-aws-syd in order to run Virtualbox/Vagrant, but I think isolating the brains (scheduler) from the brawn (heavy build jobs) is sensible.

**Comment by mhidas** [comment]
I think most of the artifacts download ok now, but I still get a problem with the "IMAS Fluorometry" one:

```
==> po: * imos_artifacts_deploy[aodn_imas_fluorometry-aodn_imas_fluorometry] action deploy
==> po: [2016-05-30T14:19:58+10:00] ERROR: Error loading data bag (passwords, jenkins-api).
==> po: [2016-05-30T14:19:58+10:00] WARN: Not using authentication for jenkins download from 'https://ci.aodn.org.au/job/talend_build/lastSuccessfulBuild'
==> po: [2016-05-30T14:19:58+10:00] INFO: Downloading artifact version ''
==> po: 
==> po:     
==> po: 
==> po:     ================================================================================
==> po:     Error executing action `deploy` on resource 'imos_artifacts_deploy[aodn_imas_fluorometry-aodn_imas_fluorometry]'
==> po:     ================================================================================
==> po:     
==> po: 
==> po: 
==> po:     TypeError
==> po:     
==> po: ---------
==> po:     no implicit conversion of nil into String
==> po:     
==> po:     Cookbook Trace:
==> po:     ---------------
==> po:     /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/imos_artifacts/libraries/fetcher_jenkins.rb:86:in `+'
==> po:     
==> po: /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/imos_artifacts/libraries/fetcher_jenkins.rb:86:in `cache'
==> po: 
==> po:     
==> po: /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/imos_artifacts/libraries/fetcher.rb:28:in `fetch_jenkins_artifact'
==> po:     /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/imos_artifacts/libraries/fetcher.rb:21:in `fetch_artifact'
==> po:     /tmp/vagrant-chef/0676eccd8491834c287a4b721d2eb0b5/cookbooks/imos_artifacts/providers/deploy.rb:18:in `block in class_from_file'
==> po:     
==> po: 
```

If I remove "aodn_imas_fluorometry" from the node definition, the provision runs fine.

**Comment by lwgordonimos** [comment]
Yep I've been testing that. It's a problem with a case sensitive string comparison in the Chef caching code. For some reason, on this one it tries to use a lower-case filename when trying to find a match in the list of all artifacts.

Replacing:
`if artifact['fileName']  == artifact_manifest['filename']`
with:
`if artifact['fileName'].upcase  == artifact_manifest['filename'].upcase`
in cookbooks/imos_artifacts/libraries/fetcher_jenkins.rb resolves it, however we would need to confirm whether this is a safe assumption to make. I'm guessing it is, but not overly happy with just changing it without unnderstanding why this is the case... the filename is in the expected mixed case in the data bag for this harvester, so can't quite see yet where it is getting the lower case version from!

It looks like issue 2 I mentioned is only related to Jenkins doing a test build, so not relevant for local builds.

**Comment by danfruehauf** [comment]
My 2 cents about the whole thing:
 * Your Jenkins is exposing private jobs - BAD
 * This job didn't succeed for a while - pretty BAD

Why is that?
You removed 6-its-hob - I can see that because your Jenkins is exposed and exposing git history on chef-private

Why you need 6-its-hob:
 * To provision Jenkins (15-aws-syd) so it doesn't get cut off in the middle and exposes private jobs because it only half ran
 * Running VirtualBox - like for this job. You can't run VirtualBox on EC2, and also if you can, it's silly.
 * Trying to patch things with `proxy_exclusions` is avoiding the real problem and hacky as hell - if this is the purpose of that "feature"

**Comment by lwgordonimos** [comment]
Resolved by https://github.com/aodn/chef/pull/309

**Comment by lbesnard** [comment]
:+1: @lwgordonimos  , makes our life easier !

**Comment by mhidas** [comment]
I just got a failed provision again. Same error as in https://github.com/aodn/chef/issues/289#issuecomment-222411700 above

**Comment by mhidas** [comment]
Never mind! I was on an old branch and forgot to rebase.
